#!/bin/sh

mkdir -p dist

if ! test -f dist/bootstrap.min.css
then
	curl -s https://bootswatch.com/5/darkly/bootstrap.min.css > dist/bootstrap.min.css
fi

if ! test -f dist/feather-sprite.svg
then
	curl -s https://unpkg.com/feather-icons@4.29.0/dist/feather-sprite.svg > dist/feather-sprite.svg
fi

cp react-widgets.css style.css dist/
