#!/bin/sh

mkdir -p dist

hget="curl"
# if we don't have curl we may have wget(1) from busybox(1)
if ! which curl >/dev/null
then
	hget="wget -O -"
fi

$hget https://bootswatch.com/5/darkly/bootstrap.min.css 2>/dev/null > dist/bootstrap.min.css

$hget https://unpkg.com/feather-icons@4.29.0/dist/feather-sprite.svg 2>/dev/null > dist/feather-sprite.svg
